name: Check Schema with Apollo Studio

on:
  pull_request:
    branches: [main]
  workflow_call:
    outputs:
      schema:
        description: "Name of the schema file from the artifact"
        value: ${{ jobs.test-and-export-schema.outputs.schema }}
      schema_artifact:
        description: "Name of the artifact to download to get the schema"
        value: ${{ jobs.test-and-export-schema.outputs.schema_artifact }}

jobs:
  test-and-export-schema:
    name: Test and export schema
    uses: ./.github/workflows/test.yml

  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      has-apollo-key: ${{ steps.apollo-key.outputs.defined }}
      has-apollo-graph-name: ${{ steps.apollo-graph-name.outputs.defined }}
    steps:
      - id: apollo-key
        if: "${{ env.APOLLO_KEY != '' }}"
        run: echo "::set-output name=defined::true"
        env:
          MY_KEY: ${{ secrets.APOLLO_KEY }}

      - id: apollo-graph-name
        if: "${{ env.APOLLO_GRAPH_NAME != '' }}"
        run: echo "::set-output name=defined::true"
        env:
          MY_KEY: ${{ secrets.APOLLO_GRAPH_NAME }}

  check-schema:
    needs: [test-and-export-schema, check-secrets]
    name: Check schema with Apollo Studio
    runs-on: ubuntu-latest
    environment: apollo
    env:
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.test-and-export-schema.outputs.schema_artifact }}
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Check new schema with Apollo Studio
        if: needs.check-secret.outputs.has-apollo-key == 'true' && needs.check-secret.outputs.has-apollo-graph-name != 'true'
        run: |
          rover subgraph check ${{ secrets.APOLLO_GRAPH_NAME }}@current --schema ${{ needs.test-and-export-schema.outputs.schema }} --name ${{ secrets.SUBGRAPH_NAME }}
      - name: No Apollo Studio Api Key is set
        if: needs.check-secret.outputs.has-apollo-key != 'true'
        run:
          echo "::warning
          file=.github/workflows/publish-schema.yml,line=13,col=1,endColumn=1::No
          Apollo Studio Api Key is set in repository. Set this in the repository
          secrets under APOLLO_KEY"
      - name: No Apollo Studio Graph Name is set
        if: needs.check-secret.outputs.has-apollo-graph-name != 'true'
        run:
          echo "::warning
          file=.github/workflows/publish-schema.yml,line=13,col=1,endColumn=1::No
          Apollo Studio Graph Name is set in repository. Set this in the
          repository secrets under APOLLO_GRAPH_NAME"
